version: 0.0
os: linux
files:
  - source: /target/CustomerOnBoard-Raghib-0.0.1
    destination: /usr/share/tomcat7/webapps
hooks:
  BeforeInstall:
    - location: setup.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop.sh
      timeout: 300
      runas: root
